name: Example Workflow

on:
  workflow_dispatch:

jobs:
  a:
    runs-on: ubuntu-latest
    outputs:
      variable: ${{ steps.set-variable.outputs.variable }}
    steps:
    - name: Set and print variable
      run: |
        variable=1
        echo "variable=$variable"
