name: Example Workflow

on:
  workflow_dispatch:

jobs:
  a:
    runs-on: ubuntu-latest
    outputs:
      variable: ${{ steps.set-variable.outputs.variable }}
    steps:
    - name: Set variable
      id: set-variable
      run: echo "variable=1" >> $GITHUB_ENV

  b:
    needs: a
    runs-on: ubuntu-latest
    if: needs.a.outputs.variable == 'variable=1'
    steps:
    - name: B is working
      run: echo "b is working"

  c:
    needs: a
    runs-on: ubuntu-latest
    if: needs.a.outputs.variable == '2'
    steps:
    - name: C is working
      run: echo "c is working"
