# this workflow is used by every pull request

# имя, чтобы отображалось в интерфейсе
name: check table columns

# тут список событий, на который экшен должен запускаться
on: 
  # пусть гоняется на пулл-реквест
  pull_request:
  
# список того, что нужно делать
# каждый job будет выводиться отдельным элементом слева UI
jobs:
  # уникальное имя элемента слева UI
  Install_Py:
    # указываем на какое машине гоняем
    runs-on: ubuntu-latest
    # список упорядоченных шагов, которые будут последовательно выполняться
    steps:
      # checkout делает pull репозитория и ветки, в котором запущен. Таким образом мы получаем доступ к коду
      - uses: actions/checkout@v3
      # setup-python устанавливает Py
      - uses: actions/setup-python@v4
        # передаем параметры при установке данного экшена
        with:
          python-version: "3.9"
          architecture: "x64"
  
  Convert_TSV_to_JSON:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/papb/tsv-json
      - name: Install_tsv-json
        run: | 
            $ npm install tsv-json
            const { tsv2json, json2tsv } = require('tsv-json')
            console.log(tsv2json('OilMetagenomesDB/crude_oil/samples/samples.json'))
