# this workflow is used by every pull request

# имя, чтобы отображалось в интерфейсе
name: check table columns

# тут список событий, на который экшен должен запускаться
# пусть гоняется на пулл-реквест
on: [pull_request]
  
# список того, что нужно делать
# каждый job будет выводиться отдельным элементом слева UI
jobs:
  # уникальное имя элемента слева UI
  Check_tsv:
    # указываем на какое машине гоняем
    runs-on: ubuntu-latest
    # список упорядоченных шагов, которые будут последовательно выполняться
    steps:
      # checkout делает pull репозитория и ветки, в котором запущен. Таким образом мы получаем доступ к коду
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pandas
      
      - name: Convert TSV to JSON
        run: |
          python tsv2json.py crude_oil_samples.tsv crude_oil_samples.json
        working-directory: crude_oil/samples
  
      - name: Commit changes
        uses: EndBug/add-and-commit@v7.0.0
        with:
          message: "Convert TSV to JSON"
          add: "crude_oil_samples.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: OilMetagenomesDB/crude_oil/samples/samples.json
          INPUT_JSONS: OilMetagenomesDB/crude_oil/samples/crude_oil_samples.json
