# this workflow is used by every pull request

# имя, чтобы отображалось в интерфейсе
name: check table columns

# тут список событий, на который экшен должен запускаться
# пусть гоняется на пулл-реквест
on: [pull_request]
  
# список того, что нужно делать
# каждый job будет выводиться отдельным элементом слева UI
jobs:
  # уникальное имя элемента слева UI
  Check_tsv:
    # указываем на какое машине гоняем
    runs-on: ubuntu-latest
    # список упорядоченных шагов, которые будут последовательно выполняться
    steps:
      # checkout делает pull репозитория и ветки, в котором запущен. Таким образом мы получаем доступ к коду
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pandas
      - name: Convert TSV to JSON
        run: |
          python tsv2json.py crude_oil_samples.tsv crude_oil_samples.json
        working-directory: crude_oil/samples
      - name: Debug file path
        run: |
          pwd
          ls crude_oil/samples
      - name: Save artifact
        id: Save_artifact
        run: |  
          echo "::set-output name=output_file::crude_oil_samples.json"
          echo "::set-output name=artifact_name::crude_oil_samples"
          echo "::set-output name=artifact_path::${{ github.workspace }}/crude_oil/samples/crude_oil_samples.json"
      - name: Check output file path
        run: |
          ls crude_oil/samples/*
      - name: Upload output file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.Save_artifact.outputs.artifact_name }}
          path: ${{ steps.Save_artifact.outputs.artifact_path }}
      # checkout делает pull репозитория и ветки, в котором запущен. Таким образом мы получаем доступ к коду
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: crude_oil_samples
          path: crude_oil/samples
      - name: Debug file path
        run: |
          pwd
          ls crude_oil/samples
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ${{ env.GITHUB_WORKSPACE }}/crude_oil/samples/samples.json
          INPUT_JSONS: ${{ env.GITHUB_WORKSPACE }}/crude_oil/samples/crude_oil_samples.json
