name: test
on:
  workflow_dispatch:
jobs:
  a:
    name: a
    runs-on: ubuntu-latest
    steps:
      - run: echo "A"
      - name: Set run_job_b variable
        id: set
        run: |
          echo "yes" > run_job_b.txt

  b:
    name: b
    needs: a
    runs-on: ubuntu-latest
    if: ${{ fileExists('run_job_b.txt') }}
    steps:
      - run: echo "B"
