name: Example Workflow

on:
  workflow_dispatch:

jobs:
  a:
    runs-on: ubuntu-latest
    outputs:
      variable_b: ${{ steps.set-variable.outputs.variable_b }}
      variable_c: ${{ steps.set-variable.outputs.variable_c }}
    steps:
    - name: Set variables
      run: |
        echo "variable_b=1" >> $GITHUB_ENV
        echo "variable_c=2" >> $GITHUB_ENV
    - name: Set output variables
      id: set-variable
      run: |
        echo "variable_b=1" >> variable_b.txt
        echo "variable_c=2" >> variable_c.txt
    - name: Set outputs from files
      run: |
        echo "variable_b=$(cat variable_b.txt)" >> $GITHUB_ENV
        echo "variable_c=$(cat variable_c.txt)" >> $GITHUB_ENV

  b:
    needs: a
    runs-on: ubuntu-latest
    if: needs.a.outputs.variable_b == '1'
    steps:
    - name: B is working
      run: echo "b is working"

  c:
    needs: a
    runs-on: ubuntu-latest
    if: needs.a.outputs.variable_c == '2'
    steps:
    - name: C is working
      run: echo "c is working"
