name: test
on:
  workflow_dispatch:
jobs:
  a:
    name: a
    runs-on: ubuntu-latest
    steps:
      - run: echo "A"
      - name: Set run_job_b variable
        id: set
        run: |
          echo "run_job_b=yes" >> $GITHUB_ENV

  b:
    name: b
    needs: a
    runs-on: ubuntu-latest
    if: ${{ env.run_job_b == 'yes' }}
    steps:
      - run: echo "B"
