# this workflow is used by every pull request

# имя, чтобы отображалось в интерфейсе
name: check table columns

# тут список событий, на который экшен должен запускаться
# пусть гоняется на пулл-реквест
on: [pull_request]
  
# список того, что нужно делать
# каждый job будет выводиться отдельным элементом слева UI
jobs:
  # уникальное имя элемента слева UI
  Check_tsv:
    # указываем на какое машине гоняем
    runs-on: ubuntu-latest
    # список упорядоченных шагов, которые будут последовательно выполняться
    steps:
      # checkout делает pull репозитория и ветки, в котором запущен. Таким образом мы получаем доступ к коду
      - uses: actions/checkout@v3
      # setup-python устанавливает Py
      - uses: actions/setup-python@v4
        # передаем параметры при установке данного экшена
        with:
          python-version: "3.9"
          architecture: "x64"
      # https://github.com/dhimmel/plostime/blob/master/tsv-to-json.ipynb
      - name: Run script tsv to json
        run: python .github/workflows/tsv2json.py
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: OilMetagenomesDB/crude_oil/samples/samples.json
          INPUT_JSONS: OilMetagenomesDB/crude_oil/samples/crude_oil_samples.json
