name: Check modified files

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pandas
            
      - name: Check token availability
        run: | 
            echo "Token exists if following is true: ${{ !!secrets.GITHUB_TOKEN }}"
          
      - name: Check modified files
        run: |
            MODIFIED_FILES=$(git diff --name-only origin/main...HEAD)
            ERROR=false
            for FILE in $MODIFIED_FILES
            do
              FILENAME=$(basename $FILE)
              if [[ $FILENAME != "common_libraries.tsv" && $FILENAME != "common_samples.tsv" ]]
              then
                echo -e "\e[31mInvalid file modified: $FILE\e[0m"
                ERROR=true
              fi
            done
            if $ERROR
            then
              exit 1
            fi
            MODIFIED_FILES=$(echo $MODIFIED_FILES | tr '\n' ' ')
            echo "MODIFIED_FILES=$MODIFIED_FILES" >> $GITHUB_ENV
            echo -e "\033[38;5;40mNo modified files except data\033[0m"

      - name: Run check_samples.yml и/или check_libraries.yml
        run: |
            MODIFIED_FILES=(${{ env.MODIFIED_FILES }})
            for FILE in "${MODIFIED_FILES[@]}"
            do
                if [[ $FILE == *"common_libraries.tsv"* ]]; then
                export FILE_PATH=${{ github.workspace }}/$FILE
                echo "Run check_libraries.yml workflow"
                curl -X POST \
                    -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    "https://api.github.com/repos/agni-bioinformatics-lab/OilMetagenomesDB/actions/workflows/check_libraries.yml/dispatches" \
                    -d '{"ref":"main"}'
                elif [[ $FILE == *"common_samples.tsv"* ]]; then
                export FILE_PATH=${{ github.workspace }}/$FILE
                echo "Run check_samples.yml workflow"
                curl -X POST \
                    -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    "https://api.github.com/repos/agni-bioinformatics-lab/OilMetagenomesDB/actions/workflows/check_samples.yml/dispatches" \
                    -d '{"ref":"main"}'
                fi
            done