name: test
on:
  workflow_dispatch:
jobs:
  a:
    name: a
    runs-on: ubuntu-latest
    steps:
      - run: echo "A"
      - name: Set run_job_b variable
        id: set
        run: |
          echo "run_job_b=yes" >> run_job_b.txt
      - name: Upload run_job_b artifact
        uses: actions/upload-artifact@v2
        with:
          name: run_job_b
          path: run_job_b.txt

  b:
    name: b
    needs: a
    runs-on: ubuntu-latest
    steps:
      - name: Download run_job_b artifact
        uses: actions/download-artifact@v2
        with:
          name: run_job_b
      - name: Check run_job_b variable
        run: |
          VARIABLE=$(cat run_job_b.txt)
          if [ "$VARIABLE" = "yes" ]; then
            echo "B"
          else
            echo "Skipping job B"
          fi
