name: test
on:
  workflow_dispatch:
jobs:
  a:
    name: a
    runs-on: ubuntu-latest
    steps:
      - run: echo "A"
      - name: Set run_job_b variable
        id: set
        run: |
          echo "run_job_b" >> run_job_b.txt
      - name: Upload run_job_b artifact
        uses: actions/upload-artifact@v2
        with:
          name: run_job_b
          path: run_job_b.txt

  b:
    name: b
    needs: a
    runs-on: ubuntu-latest
    steps:
      - name: Download run_job_b artifact
        uses: actions/download-artifact@v2
        with:
          name: run_job_b
      - name: Check run_job_b variable
        run: |
          VARIABLE=$(cat run_job_b.txt)
          if [ "$VARIABLE" = "run_job_b" ]; then
            echo "B is going to work"
          else
            echo "Skipping job B and go to c"
            exit 0
          fi
      - name: Check run_job_b variable
        run: |
          echo "B is working now"

  c:
    name: c
    needs: a
    runs-on: ubuntu-latest
    steps:
      - name: Check c
        run: | 
          echo "C is working now"
